# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fib():
    fib1 = 1
    fib2 = 2
    yield fib1
    yield fib2
    while True:
        fib1,fib2 = fib2, fib1 + fib2
        yield  fib2

def sub_fib(start_num,stop_num):
    for cur in fib():
        if cur > stop_num:
            return
        if cur >= start_num:
            yield cur

list_num = list(sub_fib(1,4000001))
print(list_num)
print(sum(list_num))
print(sum([1, 2, 3, 5, 8, 13, 21, 34, 55, 89]))
